### PR TITLE
Sean wang budge create model

### PR DESCRIPTION
**Pull request by w-disheng**

### CODE REVIEW

**Review by chucklui — APPROVED** [review]
looks good!

**Comment by francisli** [comment]
@chucklui @w-disheng "Budget" was misspelled as "Budge" so now you have a "Budges" table... how did this pass review, did you actually stop to look at the changes?!

**Comment by chucklui** [comment]
I overlooked it that was my fault. I'll be more careful next time

**Comment by w-disheng** [comment]
> I overlooked it that was my fault. I'll be more careful next time

Sorry chuck I am bad speller. I will fix this now and please review it again!

**Pull request merged**
